# Generated by Django 4.0.1 on 2022-04-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sellerdetailsmodel',
            table='seller_details',
        ),
    ]
