# Generated by Django 4.0.3 on 2022-04-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_alter_sellerdetailsmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('seller_id', models.IntegerField()),
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory', models.CharField(max_length=50)),
                ('pro_name', models.CharField(max_length=100)),
                ('model_no', models.CharField(max_length=50)),
                ('pro_prize', models.CharField(max_length=50)),
                ('pro_image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
    ]
