# Generated by Django 4.0.1 on 2022-04-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0003_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUploadModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('seller_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_images', models.ImageField(upload_to='images/')),
                ('pro_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerapp.productmodel')),
            ],
        ),
    ]
