# Generated by Django 4.0.1 on 2022-04-18 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0005_alter_productuploadmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuploadmodel',
            name='pro_details',
            field=models.ForeignKey(db_column='product_details', on_delete=django.db.models.deletion.CASCADE, to='sellerapp.productmodel'),
        ),
    ]
