# Generated by Django 4.0.3 on 2022-04-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0006_alter_productuploadmodel_pro_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetailsmodel',
            name='status',
            field=models.CharField(default='pending', max_length=40),
        ),
    ]
