# Generated by Django 4.0.1 on 2022-04-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0007_sellerdetailsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='seller_name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
