# Generated by Django 4.0.1 on 2022-04-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0008_productmodel_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Pro_images',
            field=models.ImageField(default='mutiple images', upload_to='images/'),
        ),
    ]
