# Generated by Django 4.0.1 on 2022-04-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0009_productmodel_pro_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='pro_discount',
            field=models.CharField(default='discount', max_length=50),
        ),
    ]
