# Generated by Django 4.0.3 on 2022-08-28 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0012_productmodel_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.sellerdetailsmodel'),
        ),
    ]
