# Generated by Django 4.0.3 on 2022-08-28 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0015_alter_productuploadmodel_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuploadmodel',
            name='pro_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.productmodel'),
        ),
    ]
