# Generated by Django 4.0.3 on 2022-08-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0016_alter_productuploadmodel_pro_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuploadmodel',
            name='product_images',
        ),
        migrations.AddField(
            model_name='productuploadmodel',
            name='product_images1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='productuploadmodel',
            name='product_images2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='productuploadmodel',
            name='product_images3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='productuploadmodel',
            name='product_images4',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='productuploadmodel',
            name='product_images5',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
