# Generated by Django 4.0.3 on 2022-08-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_userdetailsmodel_table'),
        ('sellerapp', '0018_alter_productmodel_pro_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuploadmodel',
            name='product_watchlist',
            field=models.ManyToManyField(blank=True, help_text='watchlist', related_name='my_watchlist', to='userapp.userdetailsmodel'),
        ),
    ]
