# Generated by Django 4.0.3 on 2022-09-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0019_productuploadmodel_product_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pro_discount',
            field=models.IntegerField(null=True),
        ),
    ]
