# Generated by Django 4.0.3 on 2022-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0022_alter_productmodel_pro_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='purchasedcount',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='productuploadmodel',
            name='purchasedcount',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
