# Generated by Django 4.0.3 on 2022-09-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0023_productmodel_purchasedcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_review',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
