# Generated by Django 4.0.3 on 2022-09-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0024_productmodel_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='user_review_count',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
