# Generated by Django 4.0.3 on 2022-09-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0025_productmodel_user_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='purchasedcount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
