# Generated by Django 4.0.3 on 2022-09-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0026_alter_productmodel_purchasedcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='purchasedcount',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
    ]
