# Generated by Django 4.0.3 on 2022-09-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0027_alter_productmodel_purchasedcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='purchasedcount',
            field=models.BigIntegerField(default=0, max_length=200, null=True),
        ),
    ]
