# Generated by Django 4.0.3 on 2022-09-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0028_alter_productmodel_purchasedcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_uploaded_status',
            field=models.CharField(default='pending', max_length=200, null=True),
        ),
    ]
