# Generated by Django 4.0.3 on 2022-09-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_product_qty',
            field=models.CharField(default=1, help_text='product_quantity', max_length=50),
        ),
    ]
