# Generated by Django 4.0.3 on 2022-09-07 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_userdetailsmodel_table'),
        ('mainapp', '0002_alter_cartmodel_cart_product_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(help_text='customer_address', max_length=200)),
                ('city', models.CharField(max_length=20, null=True)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('flat_no', models.CharField(max_length=100, null=True)),
                ('contact_no', models.CharField(max_length=15, null=True)),
                ('address_name', models.CharField(max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.userdetailsmodel')),
            ],
            options={
                'db_table': 'customer_address',
            },
        ),
    ]
