# Generated by Django 4.0.3 on 2022-09-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='address_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
