# Generated by Django 4.0.3 on 2022-09-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_customeraddress_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='state',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='landmark',
            field=models.CharField(help_text='landmark', max_length=200, null=True),
        ),
    ]
