# Generated by Django 4.0.3 on 2022-09-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0022_alter_productmodel_pro_discount'),
        ('userapp', '0002_alter_userdetailsmodel_table'),
        ('mainapp', '0006_alter_customeraddress_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModels',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_unique_id', models.CharField(help_text='order_id_from_razorpay', max_length=100, null=True)),
                ('order_payment_id', models.CharField(help_text='Payment_id_from_razorpay', max_length=100, null=True)),
                ('order_product_price', models.IntegerField(help_text='order_price', null=True)),
                ('order_product_qty', models.IntegerField(help_text='order_product_qty', null=True)),
                ('order_product_amount', models.IntegerField(help_text='order_product_amount', null=True)),
                ('order_date', models.DateTimeField(auto_now=True, help_text='order_date')),
                ('order_payment_status', models.CharField(default='Pending', help_text='payment_status', max_length=20)),
                ('order_status', models.CharField(default='Pending', help_text='order_status', max_length=100)),
                ('order_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='mainapp.customeraddress')),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='userapp.userdetailsmodel')),
                ('order_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.productmodel')),
                ('order_product_seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_ordered_products', to='sellerapp.sellerdetailsmodel')),
            ],
            options={
                'db_table': 'order_details',
            },
        ),
    ]
