# Generated by Django 4.0.3 on 2022-09-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0022_alter_productmodel_pro_discount'),
        ('mainapp', '0007_ordersmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodels',
            name='order_product2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.productmodel'),
        ),
        migrations.AlterField(
            model_name='ordersmodels',
            name='order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.productuploadmodel'),
        ),
    ]
