# Generated by Django 4.0.3 on 2022-09-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_feedbackmodel_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='feedback_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
