# Generated by Django 4.0.3 on 2022-09-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_feedbackmodel_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='feedback_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='feedback_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
