# Generated by Django 4.0.3 on 2022-09-10 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0022_alter_productmodel_pro_discount'),
        ('mainapp', '0012_feedbackmodel_feedback_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='feedback_product2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.productmodel'),
        ),
    ]
