# Generated by Django 4.0.3 on 2022-09-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_ordersmodels_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodels',
            name='order_address',
            field=models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_address', to='mainapp.customeraddress'),
        ),
    ]
