# Generated by Django 4.0.3 on 2022-09-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_ordersmodels_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodels',
            name='address_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordersmodels',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordersmodels',
            name='contact_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ordersmodels',
            name='flat_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordersmodels',
            name='landmark',
            field=models.CharField(help_text='landmark', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ordersmodels',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
