# Generated by Django 4.0.1 on 2022-04-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetailsmodel',
            table='user_details',
        ),
    ]
