# Generated by Django 4.0.3 on 2022-09-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_userdetailsmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsmodel',
            name='customer_cart_address',
            field=models.IntegerField(default=0, help_text='address_id'),
        ),
    ]
